In [3]:
import numpy as np

In [4]:
# array 의 생성
a = [1,2,3,4,5]
b = [ 5,4,3,2,1]

In [5]:
a = np.array(a, int)
a

array([1, 2, 3, 4, 5])

In [8]:
test_array = np.array(["1", "4", 5, 8] , float)   # shift + Tab 버튼을 누르면 docstring이 보임.
test_array

array([1., 4., 5., 8.])

In [9]:
type(test_array)

numpy.ndarray

In [10]:
type(test_array[3])

numpy.float64

In [11]:
test_array = np.array([1, 4, 5, "8"], float) # String Type Data를 입력해도
test_array

array([1., 4., 5., 8.])

In [13]:
type(test_array[3]) #Float type 으로 자동 형변환 실시

numpy.float64

In [14]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]
a[0] is b[-1]

True

In [15]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

In [16]:
test_array.dtype #Array배열 전체의 데이터 타입을 반환함

dtype('float64')

In [17]:
a = [[1,2,3] , [4,5,6], [4,5,6]]

In [18]:
np.array(a).shape

(3, 3)

In [19]:
#array shape
vector = [1,2,3,4]
np.array(vector, int).shape

(4,)

In [20]:
matrix = [[1,2,5,8,] , [1,2,5,8], [1,2,5,8]]
np.array(matrix, int)

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [23]:
tensor = [
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
    [[1,2,5,8],[1,2,5,8],[1,2,5,8]],
]
np.array(tensor, int).shape

(4, 3, 4)

In [24]:
np.array(tensor, int).ndim

3

In [25]:
np.array(tensor, int).size

48

In [26]:
#numpy dtype
a = np.array([[1,2,3], [4,5,6]], dtype=np.int8)

In [28]:
a.dtype

dtype('int8')

In [30]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.float32).nbytes

24

In [32]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.int32).nbytes

24

In [33]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.int8).nbytes

6

In [31]:
np.array([[1,2,3], [4.5,"5","6"]], dtype=np.float64).nbytes

48