In [1]:
import numpy as np

In [2]:
#arange
list(range(0,10,3))

[0, 3, 6, 9]

In [3]:
type(list(range(30)))

list

In [4]:
#range : list의 range 와 같은 효과,
#integer로 0부터 29까지 배열추출
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.arange(0,5,0.5)

In [6]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [7]:
#ones,zeros & empty
#10 - zero vector 생성
np.zeros(shape=(10,),
                dtype = np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [8]:
np.zeros((2,5))  #2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(shape=(10, ), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [18]:
np.empty(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [11]:
np.empty((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
test_matrix = np.arange(100).reshape(5,-1)
test_matrix.shape

(5, 20)

In [20]:
test_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [21]:
np.zeros_like(test_matrix, dtype=np.float32)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [22]:
#eye, identity, &diagonal
np.identity(n=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [23]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(3,5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
matrix = np.arange(12).reshape(3,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
np.diag(matrix, k=-1)

array([4, 9])

In [30]:
np.diag(matrix, k=1)

array([ 1,  6, 11])

In [31]:
#numpy random
np.random.normal(0,1,10).reshape(2,5)

array([[ 1.42035705, -0.92030127,  0.05652617, -0.06946909, -1.65007012],
       [ 0.32999468,  1.00686675, -0.49627685,  0.50572518, -1.05169937]])

In [32]:
np.random.exponential(scale=2, size=100)

array([2.83657291e+00, 3.88186685e+00, 2.15683913e-01, 3.19441267e+00,
       2.74174128e+00, 4.57397739e+00, 1.30430188e+00, 1.79818918e+00,
       2.50305297e+00, 2.10711477e+00, 1.29610141e+00, 2.52873986e+00,
       4.90010852e-01, 2.15388231e+00, 1.27667720e+00, 1.55903730e+00,
       3.49431001e+00, 1.40822459e+00, 1.13284712e+00, 1.46797783e+00,
       4.13558434e-01, 2.43275735e+00, 3.27060898e-01, 1.12648344e+00,
       5.62943300e+00, 1.36996484e+00, 2.66893695e+00, 1.56578668e+00,
       2.08661391e+00, 9.25576677e-01, 6.90620995e-01, 1.86338650e-01,
       3.54659522e+00, 1.10649906e+00, 4.88691656e-01, 5.79063795e-01,
       4.28331521e-01, 1.99969742e-01, 4.42805015e-01, 1.09957281e+00,
       6.42971972e-01, 8.32776170e-01, 2.23049071e+00, 3.08747223e+00,
       6.21857453e-01, 7.54143910e-01, 1.03746698e+00, 2.08139885e+00,
       1.84984304e+00, 1.55844907e+00, 1.88813430e-01, 6.08754336e-01,
       3.20091859e+00, 1.36735040e+00, 3.85595672e+00, 4.31635877e-01,
      