In [1]:
import numpy as np

In [2]:
#array operation
test_a = np.array([[1,2,3], [4,5,6]], float)

In [3]:
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
test_a + test_a #matrix + matrix 

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [5]:
test_a - test_a #matrix - matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
test_a * test_a #matrix 내 element 들간의  같은 위치에 있는 값들끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [7]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a - matrix_a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
# dot product
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [9]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [10]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [11]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [15]:
#broadcasting
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [16]:
test_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [17]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [18]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [19]:
test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [20]:
test_matrix /5 

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [21]:
test_matrix // 2

array([[0., 1., 1.],
       [2., 2., 3.]])

In [22]:
test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [23]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)

In [24]:
test_vector

array([10, 20, 30])

In [25]:
test_vector.reshape(-1,3).T + test_vector

array([[20, 30, 40],
       [30, 40, 50],
       [40, 50, 60]])

In [26]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [30]:
def sclar_vector_product(scalar, vector): 
    result = []
    for value in vector: 
        result.append(scalar * value)
    return result 
    
iternation_max = 100000000
vector = list(range(iternation_max)) 
scalar = 2
%timeit sclar_vector_product(scalar, vector) # for loop을 이용한 성능

4.51 s ± 55.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [31]:
%timeit [scalar * value for value in range(iternation_max)]
# list comprehension을 이용한 성능

3.13 s ± 21 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [32]:
%timeit np.arange(iternation_max) * scalar # numpy를 이용한 성능

99.8 ms ± 738 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
