In [44]:
import numpy as np

In [2]:
# all & any
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [4]:
a < 1

array([ True, False, False, False, False, False, False, False, False,
       False])

In [5]:
a < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [6]:
np.all(a<10)

True

In [7]:
a<5

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [8]:
np.all(a<5)

False

In [9]:
np.any(a>5)

True

In [10]:
np.any(a<0)

False

In [11]:
np.all(a>5), np.all(a<10)

(False, True)

In [12]:
#comparision operation
test_a = np.array([1,3,0], float)
test_b = np.array([5,2,1], float)

In [13]:
test_a > test_b

array([False,  True, False])

In [14]:
test_a >= test_b

array([False,  True, False])

In [15]:
(test_a > test_b).any()

True

In [16]:
(test_a > test_b).all()

False

In [18]:
a = np.array([1,3,0], float)
a> 0

array([ True,  True, False])

In [19]:
a

array([1., 3., 0.])

In [20]:
np.logical_and(a>0, a<3) # and 조건의 condition

array([ True, False, False])

In [21]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [22]:
c = np.array([False, True, False], bool)
c

array([False,  True, False])

In [23]:
np.logical_or(b,c) #or 조건의 condition

array([ True,  True,  True])

In [24]:
# np.where 중요 많이 사용됨.
a

array([1., 3., 0.])

In [25]:
np.where(a>5)

(array([], dtype=int64),)

In [26]:
np.where(a<3)[0]

array([0, 2])

In [27]:
np.where(a<3,3,2) #where(condition, TRUE, FALSE)

array([3, 2, 3])

In [30]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
np.where(a>10)

(array([6, 7, 8, 9]),)

In [45]:
a = np.array([1, np.NAN, np.inF], float)
np.isnan(a)

AttributeError: module 'numpy' has no attribute 'inF'

In [33]:
np.isfinite(a)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [35]:
# argmax & argmin
a = np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [36]:
a.argsort()

array([0, 1, 7, 2, 3, 4, 6, 5])

In [37]:
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0])

In [38]:
np.argmax(a)

5

In [39]:
np.argmin(a)

0

In [42]:
a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [43]:
np.argmax(a, axis=1), np.argmin(a, axis = 0)

(array([3, 1, 1]), array([0, 0, 2, 2]))