In [1]:
import numpy as np

In [2]:
# boolean index
test_array = np.array([1,4,0,2,3,8,9,7],float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [3]:
test_array.shape

(8,)

In [4]:
(test_array>3).shape

(8,)

In [5]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [6]:
condition = test_array < 3

In [7]:
test_array[condition]

array([1., 0., 2.])

In [9]:
#fancy index
a = np.array([2,4,6,8], float)
b = np.array([0,0,1,3,2,1], int )#반드시 integer로 선언
a[b] #bracket index, b 배열의 값을 인덱스로 하여 a의 값들을 추출함             

array([2., 2., 4., 8., 6., 4.])

In [10]:
a.take(b) #take 함수: bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])